name: backend-prod-deploy

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/opt/birf/backend
          git pull origin master
          yarn --frozen-lockfile
          NODE_ENV=production yarn build
          pm2 restart backend
          
